const profile = (definition) => Object.freeze({
  ...definition,
  atlasSet: definition.atlasSet || "starter",
  visualScale: definition.visualScale || 1,
  atlas: Object.freeze(definition.atlas),
  drives: Object.freeze(definition.drives),
  instincts: Object.freeze(definition.instincts),
  movement: Object.freeze({ navigationJump: 1, ...definition.movement }),
  favoriteToys: Object.freeze(definition.favoriteToys)
});

export const CAT_PROFILES = Object.freeze([
  profile({
    id: "byte",
    name: "Byte",
    rarity: "common",
    tagline: "balanced little debugger",
    personality: "steady · curious · friendly",
    special: "A dependable all-rounder that adapts to any toy.",
    atlas: [0, 0],
    drives: { energy: 0.74, curiosity: 0.63, affection: 0.58, playfulness: 0.56, confidence: 0.72, anger: 0.08 },
    instincts: { sleep: 1, play: 1, roam: 1, jump: 1, mischief: 1, affection: 1, temper: 0.55, petIrritation: -0.025, calmRate: 1 },
    movement: { speed: 1, jump: 1, toyForce: 1, ability: "steady" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "patches",
    name: "Patches",
    rarity: "common",
    tagline: "professional nap tester",
    personality: "sleepy · cuddly · unhurried",
    special: "Falls into longer, deeper naps—especially inside boxes.",
    atlas: [1, 0],
    drives: { energy: 0.36, curiosity: 0.34, affection: 0.76, playfulness: 0.24, confidence: 0.68, anger: 0.03 },
    instincts: { sleep: 1.78, play: 0.5, roam: 0.62, jump: 0.58, mischief: 0.42, affection: 1.35, temper: 0.22, petIrritation: -0.045, calmRate: 1.45 },
    movement: { speed: 0.56, jump: 0.68, toyForce: 0.72, ability: "deep-sleep" },
    favoriteToys: ["box"]
  }),
  profile({
    id: "marmalade",
    name: "Marmalade",
    rarity: "common",
    tagline: "toy-powered chaos",
    personality: "playful · chaotic · outgoing",
    special: "Breaks into sudden turbo sprints while chasing toys.",
    atlas: [2, 0],
    drives: { energy: 0.9, curiosity: 0.74, affection: 0.62, playfulness: 0.94, confidence: 0.76, anger: 0.06 },
    instincts: { sleep: 0.56, play: 1.62, roam: 1.12, jump: 1.28, mischief: 1.18, affection: 1, temper: 0.36, petIrritation: -0.01, calmRate: 1.1 },
    movement: { speed: 1.72, jump: 1.18, toyForce: 1.28, ability: "turbo-sprint" },
    favoriteToys: ["ball", "laser", "feather"]
  }),
  profile({
    id: "sudo",
    name: "Sudo",
    rarity: "rare",
    tagline: "must inspect everything",
    personality: "nosy · clever · independent",
    special: "Uses higher pounces to investigate interesting places.",
    atlas: [0, 1],
    drives: { energy: 0.78, curiosity: 0.96, affection: 0.48, playfulness: 0.68, confidence: 0.73, anger: 0.12 },
    instincts: { sleep: 0.72, play: 1.06, roam: 1.58, jump: 1.48, mischief: 1.12, affection: 0.82, temper: 0.58, petIrritation: 0.025, calmRate: 0.92 },
    movement: { speed: 1.18, jump: 1.38, toyForce: 0.94, ability: "high-jump" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "ember",
    name: "Ember",
    rarity: "rare",
    tagline: "short fuse, sharp paws",
    personality: "proud · moody · fearless",
    special: "Swats toys hard and quickly hisses when overstimulated.",
    atlas: [1, 1],
    drives: { energy: 0.7, curiosity: 0.54, affection: 0.25, playfulness: 0.42, confidence: 0.91, anger: 0.48 },
    instincts: { sleep: 0.82, play: 0.72, roam: 1.04, jump: 0.96, mischief: 1.32, affection: 0.48, temper: 1.58, petIrritation: 0.16, calmRate: 0.52, hissThreshold: 0.46, clawThreshold: 0.7 },
    movement: { speed: 1.08, jump: 0.94, toyForce: 1.46, ability: "power-swipe" },
    favoriteToys: ["ball"]
  }),
  profile({
    id: "glitch",
    name: "Glitch",
    rarity: "epic",
    tagline: "mischief in the machine",
    personality: "restless · tricky · unpredictable",
    special: "Randomly teleports during play and mischief.",
    atlas: [0, 2],
    drives: { energy: 0.93, curiosity: 0.88, affection: 0.38, playfulness: 0.84, confidence: 0.87, anger: 0.24 },
    instincts: { sleep: 0.54, play: 1.3, roam: 1.3, jump: 1.46, mischief: 1.9, affection: 0.62, temper: 1.08, petIrritation: 0.07, calmRate: 0.78, hissThreshold: 0.62, clawThreshold: 0.82 },
    movement: { speed: 1.32, jump: 1.2, toyForce: 1.06, ability: "teleport" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "oracle",
    name: "Oracle",
    rarity: "epic",
    tagline: "dreams between commands",
    personality: "serene · affectionate · mysterious",
    special: "Calms quickly and settles nearby cats with a quiet aura.",
    atlas: [1, 2],
    drives: { energy: 0.42, curiosity: 0.7, affection: 0.84, playfulness: 0.36, confidence: 0.88, anger: 0.02 },
    instincts: { sleep: 1.66, play: 0.62, roam: 0.84, jump: 0.72, mischief: 0.38, affection: 1.46, temper: 0.18, petIrritation: -0.055, calmRate: 1.72 },
    movement: { speed: 0.74, jump: 0.78, toyForce: 0.68, ability: "calming-aura" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "root",
    name: "Root",
    rarity: "legendary",
    tagline: "calm until challenged",
    personality: "confident · commanding · composed",
    special: "The roster's only super-bounce cat can skip a webpage tier.",
    atlas: [2, 2],
    drives: { energy: 0.82, curiosity: 0.78, affection: 0.58, playfulness: 0.64, confidence: 0.99, anger: 0.18 },
    instincts: { sleep: 0.82, play: 1.02, roam: 1.22, jump: 1.2, mischief: 1.28, affection: 0.9, temper: 0.92, petIrritation: 0.035, calmRate: 1.08, hissThreshold: 0.7, clawThreshold: 0.9 },
    movement: { speed: 1.12, jump: 1.58, navigationJump: 1.8, toyForce: 1.52, ability: "mega-jump" },
    favoriteToys: ["ball", "feather"]
  }),
  profile({
    id: "mochi",
    name: "Mochi",
    rarity: "common",
    tagline: "soft paws, cautious heart",
    personality: "shy · gentle · loyal",
    special: "Darts away from sudden cursor movement, then returns when things calm down.",
    atlasSet: "expansion",
    atlas: [0, 0],
    drives: { energy: 0.48, curiosity: 0.4, affection: 0.86, playfulness: 0.4, confidence: 0.28, anger: 0.03 },
    instincts: { sleep: 1.28, play: 0.7, roam: 0.68, jump: 0.78, mischief: 0.22, affection: 1.7, temper: 0.4, petIrritation: -0.05, calmRate: 1.5 },
    movement: { speed: 0.84, jump: 0.82, toyForce: 0.7, ability: "shy-dash" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "biscuit",
    name: "Biscuit",
    rarity: "common",
    tagline: "every toy is legally mine",
    personality: "possessive · playful · stubborn",
    special: "Bats the ball softly so it stays close enough to guard.",
    atlasSet: "expansion",
    atlas: [1, 0],
    drives: { energy: 0.78, curiosity: 0.66, affection: 0.46, playfulness: 0.86, confidence: 0.84, anger: 0.18 },
    instincts: { sleep: 0.82, play: 1.44, roam: 0.92, jump: 1.02, mischief: 1.42, affection: 0.72, temper: 0.92, petIrritation: 0.045, calmRate: 0.82, hissThreshold: 0.62, clawThreshold: 0.82 },
    movement: { speed: 1.04, jump: 1, toyForce: 0.82, ability: "toy-hoarder" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "dot",
    name: "Dot",
    rarity: "common",
    tagline: "tiny scout, enormous nerve",
    personality: "brave · busy · observant",
    special: "A smaller footprint and quick steps make every ledge worth scouting.",
    atlasSet: "expansion",
    atlas: [2, 0],
    visualScale: 0.76,
    drives: { energy: 0.88, curiosity: 0.98, affection: 0.56, playfulness: 0.72, confidence: 0.94, anger: 0.02 },
    instincts: { sleep: 0.58, play: 1.1, roam: 1.72, jump: 1.18, mischief: 0.8, affection: 0.86, temper: 0.16, petIrritation: -0.02, calmRate: 1.38 },
    movement: { speed: 1.34, jump: 1.04, toyForce: 0.58, ability: "tiny-scout" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "nimbus",
    name: "Nimbus",
    rarity: "rare",
    tagline: "takes the scenic way down",
    personality: "dreamy · mellow · trusting",
    special: "Falls slowly like a feather after every jump.",
    atlasSet: "expansion",
    atlas: [0, 1],
    drives: { energy: 0.46, curiosity: 0.7, affection: 0.82, playfulness: 0.44, confidence: 0.76, anger: 0.01 },
    instincts: { sleep: 1.5, play: 0.76, roam: 1.08, jump: 1.08, mischief: 0.3, affection: 1.42, temper: 0.14, petIrritation: -0.06, calmRate: 1.9 },
    movement: { speed: 0.78, jump: 0.94, toyForce: 0.64, ability: "feather-fall" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "echo",
    name: "Echo",
    rarity: "rare",
    tagline: "one pounce, then another",
    personality: "watchful · precise · persistent",
    special: "Adds a second mid-air hop to ordinary pounces.",
    atlasSet: "expansion",
    atlas: [1, 1],
    drives: { energy: 0.76, curiosity: 0.86, affection: 0.44, playfulness: 0.8, confidence: 0.62, anger: 0.1 },
    instincts: { sleep: 0.72, play: 1.32, roam: 1.08, jump: 1.48, mischief: 0.94, affection: 0.7, temper: 0.62, petIrritation: 0.015, calmRate: 1.02 },
    movement: { speed: 1.06, jump: 0.96, toyForce: 0.92, ability: "double-jump" },
    favoriteToys: ["feather", "laser"]
  }),
  profile({
    id: "magnet",
    name: "Magnet",
    rarity: "rare",
    tagline: "the ball comes to me",
    personality: "focused · obsessive · reserved",
    special: "Magnetic paws tug nearby balls through the air.",
    atlasSet: "expansion",
    atlas: [2, 1],
    drives: { energy: 0.66, curiosity: 0.84, affection: 0.34, playfulness: 0.92, confidence: 0.9, anger: 0.2 },
    instincts: { sleep: 0.74, play: 1.62, roam: 0.82, jump: 0.9, mischief: 1.24, affection: 0.54, temper: 0.82, petIrritation: 0.04, calmRate: 0.86, hissThreshold: 0.68, clawThreshold: 0.86 },
    movement: { speed: 0.94, jump: 0.9, toyForce: 1.08, ability: "magnet-paws" },
    favoriteToys: ["ball"]
  }),
  profile({
    id: "vanta",
    name: "Vanta",
    rarity: "epic",
    tagline: "prefers the space between pixels",
    personality: "aloof · nocturnal · suspicious",
    special: "Phases through a short stretch of space while stalking a target.",
    atlasSet: "expansion",
    atlas: [0, 2],
    drives: { energy: 0.64, curiosity: 0.88, affection: 0.16, playfulness: 0.54, confidence: 0.97, anger: 0.36 },
    instincts: { sleep: 0.96, play: 0.9, roam: 1.42, jump: 1.08, mischief: 1.7, affection: 0.3, temper: 1.34, petIrritation: 0.13, calmRate: 0.58, hissThreshold: 0.5, clawThreshold: 0.72 },
    movement: { speed: 1.16, jump: 1.06, toyForce: 1.18, ability: "shadow-phase" },
    favoriteToys: ["laser", "box"]
  }),
  profile({
    id: "prism",
    name: "Prism",
    rarity: "epic",
    tagline: "wears every feeling in color",
    personality: "empathetic · expressive · social",
    special: "Its aura changes with its mood and gentle petting calms it instantly.",
    atlasSet: "expansion",
    atlas: [1, 2],
    drives: { energy: 0.7, curiosity: 0.76, affection: 0.94, playfulness: 0.68, confidence: 0.7, anger: 0.08 },
    instincts: { sleep: 1.02, play: 1.16, roam: 0.9, jump: 0.94, mischief: 0.46, affection: 1.7, temper: 0.24, petIrritation: -0.08, calmRate: 1.72 },
    movement: { speed: 0.96, jump: 0.96, toyForce: 0.82, ability: "mood-spectrum" },
    favoriteToys: ["feather", "box"]
  }),
  profile({
    id: "nova",
    name: "Nova",
    rarity: "legendary",
    tagline: "a comet with whiskers",
    personality: "bold · adventurous · impatient",
    special: "Launches into blazing ground dashes, but still climbs one tier at a time.",
    atlasSet: "expansion",
    atlas: [2, 2],
    drives: { energy: 0.94, curiosity: 0.96, affection: 0.5, playfulness: 0.84, confidence: 1, anger: 0.12 },
    instincts: { sleep: 0.42, play: 1.42, roam: 1.68, jump: 1.16, mischief: 1.28, affection: 0.72, temper: 0.7, petIrritation: 0.02, calmRate: 0.92 },
    movement: { speed: 1.46, jump: 1.1, toyForce: 1.32, ability: "star-dash" },
    favoriteToys: ["laser", "ball"]
  })
]);

export const DEFAULT_CAT_ID = "byte";

export function getCatProfile(id) {
  return CAT_PROFILES.find((cat) => cat.id === id) || CAT_PROFILES[0];
}
