const profile = (definition) => Object.freeze({
  ...definition,
  atlasSet: definition.atlasSet || "starter",
  visualScale: definition.visualScale || 1,
  atlas: Object.freeze(definition.atlas),
  drives: Object.freeze(definition.drives),
  instincts: Object.freeze(definition.instincts),
  movement: Object.freeze({ navigationJump: 1, ...definition.movement }),
  favoriteToys: Object.freeze(definition.favoriteToys)
});

export const CAT_PROFILES = Object.freeze([
  profile({
    id: "byte",
    name: "Byte",
    rarity: "common",
    tagline: "balanced little debugger",
    personality: "steady · curious · friendly",
    special: "A dependable all-rounder that adapts to any toy.",
    atlas: [0, 0],
    drives: { energy: 0.74, curiosity: 0.63, affection: 0.58, playfulness: 0.56, confidence: 0.72, anger: 0.08 },
    instincts: { sleep: 1, play: 1, roam: 1, jump: 1, mischief: 1, affection: 1, temper: 0.55, petIrritation: -0.025, calmRate: 1 },
    movement: { speed: 1, jump: 1, toyForce: 1, ability: "steady" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "patches",
    name: "Patches",
    rarity: "common",
    tagline: "professional nap tester",
    personality: "sleepy · cuddly · unhurried",
    special: "Falls into longer, deeper naps—especially inside boxes.",
    atlas: [1, 0],
    drives: { energy: 0.36, curiosity: 0.34, affection: 0.76, playfulness: 0.24, confidence: 0.68, anger: 0.03 },
    instincts: { sleep: 1.78, play: 0.5, roam: 0.62, jump: 0.58, mischief: 0.42, affection: 1.35, temper: 0.22, petIrritation: -0.045, calmRate: 1.45 },
    movement: { speed: 0.56, jump: 0.68, toyForce: 0.72, ability: "deep-sleep" },
    favoriteToys: ["box"]
  }),
  profile({
    id: "marmalade",
    name: "Marmalade",
    rarity: "common",
    tagline: "toy-powered chaos",
    personality: "playful · chaotic · outgoing",
    special: "Breaks into sudden turbo sprints while chasing toys.",
    atlas: [2, 0],
    drives: { energy: 0.9, curiosity: 0.74, affection: 0.62, playfulness: 0.94, confidence: 0.76, anger: 0.06 },
    instincts: { sleep: 0.56, play: 1.62, roam: 1.12, jump: 1.28, mischief: 1.18, affection: 1, temper: 0.36, petIrritation: -0.01, calmRate: 1.1 },
    movement: { speed: 1.72, jump: 1.18, toyForce: 1.28, ability: "turbo-sprint" },
    favoriteToys: ["ball", "laser", "feather"]
  }),
  profile({
    id: "sudo",
    name: "Sudo",
    rarity: "rare",
    tagline: "must inspect everything",
    personality: "nosy · clever · independent",
    special: "Uses higher pounces to investigate interesting places.",
    atlas: [0, 1],
    drives: { energy: 0.78, curiosity: 0.96, affection: 0.48, playfulness: 0.68, confidence: 0.73, anger: 0.12 },
    instincts: { sleep: 0.72, play: 1.06, roam: 1.58, jump: 1.48, mischief: 1.12, affection: 0.82, temper: 0.58, petIrritation: 0.025, calmRate: 0.92 },
    movement: { speed: 1.18, jump: 1.38, toyForce: 0.94, ability: "high-jump" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "ember",
    name: "Ember",
    rarity: "rare",
    tagline: "short fuse, sharp paws",
    personality: "proud · moody · fearless",
    special: "Swats toys hard and quickly hisses when overstimulated.",
    atlas: [1, 1],
    drives: { energy: 0.7, curiosity: 0.54, affection: 0.25, playfulness: 0.42, confidence: 0.91, anger: 0.48 },
    instincts: { sleep: 0.82, play: 0.72, roam: 1.04, jump: 0.96, mischief: 1.32, affection: 0.48, temper: 1.58, petIrritation: 0.16, calmRate: 0.52, hissThreshold: 0.46, clawThreshold: 0.7 },
    movement: { speed: 1.08, jump: 0.94, toyForce: 1.46, ability: "power-swipe" },
    favoriteToys: ["ball"]
  }),
  profile({
    id: "glitch",
    name: "Glitch",
    rarity: "epic",
    tagline: "mischief in the machine",
    personality: "restless · tricky · unpredictable",
    special: "Randomly teleports during play and mischief.",
    atlas: [0, 2],
    drives: { energy: 0.93, curiosity: 0.88, affection: 0.38, playfulness: 0.84, confidence: 0.87, anger: 0.24 },
    instincts: { sleep: 0.54, play: 1.3, roam: 1.3, jump: 1.46, mischief: 1.9, affection: 0.62, temper: 1.08, petIrritation: 0.07, calmRate: 0.78, hissThreshold: 0.62, clawThreshold: 0.82 },
    movement: { speed: 1.32, jump: 1.2, toyForce: 1.06, ability: "teleport" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "oracle",
    name: "Oracle",
    rarity: "epic",
    tagline: "dreams between commands",
    personality: "serene · affectionate · mysterious",
    special: "Calms quickly and settles nearby cats with a quiet aura.",
    atlas: [1, 2],
    drives: { energy: 0.42, curiosity: 0.7, affection: 0.84, playfulness: 0.36, confidence: 0.88, anger: 0.02 },
    instincts: { sleep: 1.66, play: 0.62, roam: 0.84, jump: 0.72, mischief: 0.38, affection: 1.46, temper: 0.18, petIrritation: -0.055, calmRate: 1.72 },
    movement: { speed: 0.74, jump: 0.78, toyForce: 0.68, ability: "calming-aura" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "root",
    name: "Root",
    rarity: "legendary",
    tagline: "calm until challenged",
    personality: "confident · commanding · composed",
    special: "The roster's only super-bounce cat can skip a webpage tier.",
    atlas: [2, 2],
    drives: { energy: 0.82, curiosity: 0.78, affection: 0.58, playfulness: 0.64, confidence: 0.99, anger: 0.18 },
    instincts: { sleep: 0.82, play: 1.02, roam: 1.22, jump: 1.2, mischief: 1.28, affection: 0.9, temper: 0.92, petIrritation: 0.035, calmRate: 1.08, hissThreshold: 0.7, clawThreshold: 0.9 },
    movement: { speed: 1.12, jump: 1.58, navigationJump: 1.8, toyForce: 1.52, ability: "mega-jump" },
    favoriteToys: ["ball", "feather"]
  }),
  profile({
    id: "mochi",
    name: "Mochi",
    rarity: "common",
    tagline: "soft paws, cautious heart",
    personality: "shy · gentle · loyal",
    special: "Darts away from sudden cursor movement, then returns when things calm down.",
    atlasSet: "expansion",
    atlas: [0, 0],
    drives: { energy: 0.48, curiosity: 0.4, affection: 0.86, playfulness: 0.4, confidence: 0.28, anger: 0.03 },
    instincts: { sleep: 1.28, play: 0.7, roam: 0.68, jump: 0.78, mischief: 0.22, affection: 1.7, temper: 0.4, petIrritation: -0.05, calmRate: 1.5 },
    movement: { speed: 0.84, jump: 0.82, toyForce: 0.7, ability: "shy-dash" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "biscuit",
    name: "Biscuit",
    rarity: "common",
    tagline: "every toy is legally mine",
    personality: "possessive · playful · stubborn",
    special: "Bats the ball softly so it stays close enough to guard.",
    atlasSet: "expansion",
    atlas: [1, 0],
    drives: { energy: 0.78, curiosity: 0.66, affection: 0.46, playfulness: 0.86, confidence: 0.84, anger: 0.18 },
    instincts: { sleep: 0.82, play: 1.44, roam: 0.92, jump: 1.02, mischief: 1.42, affection: 0.72, temper: 0.92, petIrritation: 0.045, calmRate: 0.82, hissThreshold: 0.62, clawThreshold: 0.82 },
    movement: { speed: 1.04, jump: 1, toyForce: 0.82, ability: "toy-hoarder" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "dot",
    name: "Dot",
    rarity: "common",
    tagline: "tiny scout, enormous nerve",
    personality: "brave · busy · observant",
    special: "A smaller footprint and quick steps make every ledge worth scouting.",
    atlasSet: "expansion",
    atlas: [2, 0],
    visualScale: 0.76,
    drives: { energy: 0.88, curiosity: 0.98, affection: 0.56, playfulness: 0.72, confidence: 0.94, anger: 0.02 },
    instincts: { sleep: 0.58, play: 1.1, roam: 1.72, jump: 1.18, mischief: 0.8, affection: 0.86, temper: 0.16, petIrritation: -0.02, calmRate: 1.38 },
    movement: { speed: 1.34, jump: 1.04, toyForce: 0.58, ability: "tiny-scout" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "nimbus",
    name: "Nimbus",
    rarity: "rare",
    tagline: "takes the scenic way down",
    personality: "dreamy · mellow · trusting",
    special: "Falls slowly like a feather after every jump.",
    atlasSet: "expansion",
    atlas: [0, 1],
    drives: { energy: 0.46, curiosity: 0.7, affection: 0.82, playfulness: 0.44, confidence: 0.76, anger: 0.01 },
    instincts: { sleep: 1.5, play: 0.76, roam: 1.08, jump: 1.08, mischief: 0.3, affection: 1.42, temper: 0.14, petIrritation: -0.06, calmRate: 1.9 },
    movement: { speed: 0.78, jump: 0.94, toyForce: 0.64, ability: "feather-fall" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "echo",
    name: "Echo",
    rarity: "rare",
    tagline: "one pounce, then another",
    personality: "watchful · precise · persistent",
    special: "Adds a second mid-air hop to ordinary pounces.",
    atlasSet: "expansion",
    atlas: [1, 1],
    drives: { energy: 0.76, curiosity: 0.86, affection: 0.44, playfulness: 0.8, confidence: 0.62, anger: 0.1 },
    instincts: { sleep: 0.72, play: 1.32, roam: 1.08, jump: 1.48, mischief: 0.94, affection: 0.7, temper: 0.62, petIrritation: 0.015, calmRate: 1.02 },
    movement: { speed: 1.06, jump: 0.96, toyForce: 0.92, ability: "double-jump" },
    favoriteToys: ["feather", "laser"]
  }),
  profile({
    id: "magnet",
    name: "Magnet",
    rarity: "rare",
    tagline: "the ball comes to me",
    personality: "focused · obsessive · reserved",
    special: "Magnetic paws tug nearby balls through the air.",
    atlasSet: "expansion",
    atlas: [2, 1],
    drives: { energy: 0.66, curiosity: 0.84, affection: 0.34, playfulness: 0.92, confidence: 0.9, anger: 0.2 },
    instincts: { sleep: 0.74, play: 1.62, roam: 0.82, jump: 0.9, mischief: 1.24, affection: 0.54, temper: 0.82, petIrritation: 0.04, calmRate: 0.86, hissThreshold: 0.68, clawThreshold: 0.86 },
    movement: { speed: 0.94, jump: 0.9, toyForce: 1.08, ability: "magnet-paws" },
    favoriteToys: ["ball"]
  }),
  profile({
    id: "vanta",
    name: "Vanta",
    rarity: "epic",
    tagline: "prefers the space between pixels",
    personality: "aloof · nocturnal · suspicious",
    special: "Phases through a short stretch of space while stalking a target.",
    atlasSet: "expansion",
    atlas: [0, 2],
    drives: { energy: 0.64, curiosity: 0.88, affection: 0.16, playfulness: 0.54, confidence: 0.97, anger: 0.36 },
    instincts: { sleep: 0.96, play: 0.9, roam: 1.42, jump: 1.08, mischief: 1.7, affection: 0.3, temper: 1.34, petIrritation: 0.13, calmRate: 0.58, hissThreshold: 0.5, clawThreshold: 0.72 },
    movement: { speed: 1.16, jump: 1.06, toyForce: 1.18, ability: "shadow-phase" },
    favoriteToys: ["laser", "box"]
  }),
  profile({
    id: "prism",
    name: "Prism",
    rarity: "epic",
    tagline: "wears every feeling in color",
    personality: "empathetic · expressive · social",
    special: "Its aura changes with its mood and gentle petting calms it instantly.",
    atlasSet: "expansion",
    atlas: [1, 2],
    drives: { energy: 0.7, curiosity: 0.76, affection: 0.94, playfulness: 0.68, confidence: 0.7, anger: 0.08 },
    instincts: { sleep: 1.02, play: 1.16, roam: 0.9, jump: 0.94, mischief: 0.46, affection: 1.7, temper: 0.24, petIrritation: -0.08, calmRate: 1.72 },
    movement: { speed: 0.96, jump: 0.96, toyForce: 0.82, ability: "mood-spectrum" },
    favoriteToys: ["feather", "box"]
  }),
  profile({
    id: "nova",
    name: "Nova",
    rarity: "legendary",
    tagline: "a comet with whiskers",
    personality: "bold · adventurous · impatient",
    special: "Launches into blazing ground dashes, but still climbs one tier at a time.",
    atlasSet: "expansion",
    atlas: [2, 2],
    drives: { energy: 0.94, curiosity: 0.96, affection: 0.5, playfulness: 0.84, confidence: 1, anger: 0.12 },
    instincts: { sleep: 0.42, play: 1.42, roam: 1.68, jump: 1.16, mischief: 1.28, affection: 0.72, temper: 0.7, petIrritation: 0.02, calmRate: 0.92 },
    movement: { speed: 1.46, jump: 1.1, toyForce: 1.32, ability: "star-dash" },
    favoriteToys: ["laser", "ball"]
  }),
  profile({
    id: "tempo",
    name: "Tempo",
    rarity: "epic",
    tagline: "every chase has a beat",
    personality: "methodical · musical · patient",
    special: "Moves in measured rhythm bursts, pausing exactly on the beat before the next chase.",
    atlasSet: "super",
    atlas: [0, 0],
    drives: { energy: 0.72, curiosity: 0.68, affection: 0.5, playfulness: 0.8, confidence: 0.82, anger: 0.06 },
    instincts: { sleep: 0.86, play: 1.34, roam: 1.02, jump: 1.08, mischief: 0.72, affection: 0.84, temper: 0.34, petIrritation: -0.015, calmRate: 1.18 },
    movement: { speed: 1.08, jump: 1.02, toyForce: 1.02, ability: "rhythm-burst" },
    favoriteToys: ["feather", "ball"]
  }),
  profile({
    id: "blink",
    name: "Blink",
    rarity: "epic",
    tagline: "startled between seconds",
    personality: "anxious · vigilant · hypersensitive",
    special: "Fast cursor movement briefly slows nearby toys inside a protective time bubble.",
    atlasSet: "super",
    atlas: [1, 0],
    drives: { energy: 0.82, curiosity: 0.8, affection: 0.34, playfulness: 0.64, confidence: 0.32, anger: 0.22 },
    instincts: { sleep: 0.68, play: 1.08, roam: 1.34, jump: 1.2, mischief: 0.58, affection: 0.56, temper: 1.06, petIrritation: 0.08, calmRate: 0.72, hissThreshold: 0.58, clawThreshold: 0.84 },
    movement: { speed: 1.3, jump: 1.06, toyForce: 0.78, ability: "time-bubble" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "mirror",
    name: "Mirror",
    rarity: "epic",
    tagline: "applause for both of me",
    personality: "theatrical · clingy · imitative",
    special: "A delayed reflection echoes every playful move and gives the ball a second tap.",
    atlasSet: "super",
    atlas: [2, 0],
    drives: { energy: 0.7, curiosity: 0.72, affection: 0.96, playfulness: 0.82, confidence: 0.68, anger: 0.04 },
    instincts: { sleep: 0.92, play: 1.38, roam: 0.72, jump: 1.02, mischief: 0.66, affection: 1.78, temper: 0.2, petIrritation: -0.07, calmRate: 1.58 },
    movement: { speed: 0.98, jump: 1, toyForce: 0.9, ability: "mirror-clone" },
    favoriteToys: ["ball", "laser"]
  }),
  profile({
    id: "atlas",
    name: "Atlas",
    rarity: "legendary",
    tagline: "gravity has a favorite",
    personality: "stoic · protective · stubborn",
    special: "Falls with heavyweight force and ground-pounds nearby balls into the air.",
    atlasSet: "super",
    atlas: [0, 1],
    visualScale: 1.12,
    drives: { energy: 0.58, curiosity: 0.44, affection: 0.7, playfulness: 0.46, confidence: 1, anger: 0.14 },
    instincts: { sleep: 1.18, play: 0.82, roam: 0.64, jump: 0.88, mischief: 0.92, affection: 1.12, temper: 0.62, petIrritation: -0.01, calmRate: 1.04, hissThreshold: 0.7, clawThreshold: 0.9 },
    movement: { speed: 0.68, jump: 0.9, toyForce: 1.82, ability: "ground-pound" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "orbit",
    name: "Orbit",
    rarity: "legendary",
    tagline: "floats wherever curiosity leads",
    personality: "detached · whimsical · endlessly curious",
    special: "Temporarily leaves the platform system and orbits airborne cursor toys in zero gravity.",
    atlasSet: "super",
    atlas: [1, 1],
    drives: { energy: 0.76, curiosity: 1, affection: 0.28, playfulness: 0.9, confidence: 0.96, anger: 0.01 },
    instincts: { sleep: 0.66, play: 1.54, roam: 1.62, jump: 1.22, mischief: 1.08, affection: 0.44, temper: 0.1, petIrritation: -0.035, calmRate: 1.7 },
    movement: { speed: 1.04, jump: 1.08, toyForce: 0.74, ability: "zero-gravity" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "halo",
    name: "Halo",
    rarity: "legendary",
    tagline: "a warm place follows",
    personality: "caring · brave · serene",
    special: "Resting or gentle petting creates a sunbeam that restores energy and dissolves anger.",
    atlasSet: "super",
    atlas: [2, 1],
    drives: { energy: 0.54, curiosity: 0.56, affection: 0.98, playfulness: 0.42, confidence: 0.92, anger: 0 },
    instincts: { sleep: 1.46, play: 0.72, roam: 0.8, jump: 0.84, mischief: 0.24, affection: 1.84, temper: 0.08, petIrritation: -0.09, calmRate: 2.1 },
    movement: { speed: 0.82, jump: 0.88, toyForce: 0.7, ability: "sunbeam" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "melly",
    name: "Melly",
    rarity: "rare",
    tagline: "makes every ledge feel like home",
    personality: "nurturing · perceptive · soft-spoken",
    special: "Kneads a tiny comfort rhythm while resting, restoring energy and affection.",
    atlasSet: "iteration-four-a",
    atlas: [0, 0],
    drives: { energy: 0.56, curiosity: 0.66, affection: 0.94, playfulness: 0.48, confidence: 0.7, anger: 0.01 },
    instincts: { sleep: 1.32, play: 0.82, roam: 0.82, jump: 0.88, mischief: 0.3, affection: 1.76, temper: 0.12, petIrritation: -0.08, calmRate: 1.82 },
    movement: { speed: 0.86, jump: 0.9, toyForce: 0.72, ability: "comfort-knead" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "witty",
    name: "Witty",
    rarity: "epic",
    tagline: "always one thought ahead",
    personality: "quick-witted · cheeky · inventive",
    special: "Fakes the wrong direction, then snaps back toward the cursor or toy.",
    atlasSet: "iteration-four-a",
    atlas: [1, 0],
    drives: { energy: 0.82, curiosity: 0.96, affection: 0.6, playfulness: 0.9, confidence: 0.88, anger: 0.09 },
    instincts: { sleep: 0.62, play: 1.52, roam: 1.38, jump: 1.2, mischief: 1.54, affection: 0.9, temper: 0.46, petIrritation: 0.01, calmRate: 1.04 },
    movement: { speed: 1.26, jump: 1.08, toyForce: 1.04, ability: "cursor-feint" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "pixel-purl",
    name: "Pixel & Purl",
    rarity: "epic",
    tagline: "two cats, one perfectly timed ambush",
    personality: "inseparable · competitive · synchronized",
    special: "The twins tag-team the ball with a second coordinated paw strike.",
    atlasSet: "iteration-four-a",
    atlas: [2, 0],
    visualScale: 1.06,
    drives: { energy: 0.84, curiosity: 0.78, affection: 0.88, playfulness: 0.98, confidence: 0.8, anger: 0.07 },
    instincts: { sleep: 0.72, play: 1.72, roam: 0.88, jump: 1.16, mischief: 1.28, affection: 1.38, temper: 0.34, petIrritation: -0.03, calmRate: 1.18 },
    movement: { speed: 1.08, jump: 1.04, toyForce: 1.18, ability: "twin-tag-team" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "sable",
    name: "Sable",
    rarity: "common",
    tagline: "the conversation is never over",
    personality: "vocal · devoted · demanding",
    special: "Calls out with a royal yowl when ignored, then waits for an answer.",
    atlasSet: "iteration-four-a",
    atlas: [0, 1],
    drives: { energy: 0.68, curiosity: 0.7, affection: 0.86, playfulness: 0.58, confidence: 0.82, anger: 0.18 },
    instincts: { sleep: 0.86, play: 0.98, roam: 1.02, jump: 1.06, mischief: 0.7, affection: 1.62, temper: 0.78, petIrritation: 0.02, calmRate: 0.88, hissThreshold: 0.6, clawThreshold: 0.84 },
    movement: { speed: 1.02, jump: 1.02, toyForce: 0.9, ability: "royal-yowl" },
    favoriteToys: ["feather", "box"]
  }),
  profile({
    id: "mistoffelees",
    name: "Mr. Mistoffelees",
    rarity: "legendary",
    tagline: "the toy was over there a moment ago",
    personality: "showy · secretive · precise",
    special: "Performs close-up magic by vanishing a toy onto a safe nearby surface.",
    atlasSet: "iteration-four-a",
    atlas: [1, 1],
    drives: { energy: 0.76, curiosity: 0.92, affection: 0.52, playfulness: 0.86, confidence: 0.98, anger: 0.05 },
    instincts: { sleep: 0.7, play: 1.48, roam: 1.12, jump: 1.28, mischief: 1.72, affection: 0.82, temper: 0.3, petIrritation: -0.005, calmRate: 1.22 },
    movement: { speed: 1.12, jump: 1.16, toyForce: 1.08, ability: "prestidigitation" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "quickpaw",
    name: "Quickpaw",
    artDirection: -1,
    rarity: "legendary",
    tagline: "circuits the whole ledge before breakfast",
    personality: "heroic · impatient · exuberant",
    special: "Runs a full lightning lap, rebounding from both ends of its current ledge.",
    atlasSet: "iteration-four-a",
    atlas: [2, 1],
    drives: { energy: 0.98, curiosity: 0.86, affection: 0.64, playfulness: 0.94, confidence: 0.98, anger: 0.06 },
    instincts: { sleep: 0.32, play: 1.66, roam: 1.86, jump: 1.18, mischief: 1.36, affection: 0.9, temper: 0.38, petIrritation: -0.01, calmRate: 1.06 },
    movement: { speed: 1.64, jump: 1.1, toyForce: 1.22, ability: "speed-lap" },
    favoriteToys: ["laser", "ball"]
  }),
  profile({
    id: "nocturne",
    name: "Nocturne",
    rarity: "epic",
    tagline: "silent guardian of the dark tabs",
    personality: "watchful · protective · solitary",
    special: "Hooks a specific webpage landing point and reels itself directly onto that surface.",
    atlasSet: "iteration-four-a",
    atlas: [0, 2],
    drives: { energy: 0.72, curiosity: 0.82, affection: 0.3, playfulness: 0.5, confidence: 0.99, anger: 0.16 },
    instincts: { sleep: 0.8, play: 0.86, roam: 1.42, jump: 1.56, mischief: 1.06, affection: 0.5, temper: 0.74, petIrritation: 0.035, calmRate: 0.9, hissThreshold: 0.7, clawThreshold: 0.9 },
    movement: { speed: 1.14, jump: 1.12, toyForce: 1.16, ability: "grapple-glide" },
    favoriteToys: ["feather", "laser"]
  }),
  profile({
    id: "webpaw",
    name: "Webpaw",
    rarity: "epic",
    tagline: "no ledge or loose toy escapes the web",
    personality: "acrobatic · helpful · excitable",
    special: "Swings between webpage tiers and fires web tethers that tug physical toys toward its paws.",
    atlasSet: "iteration-four-a",
    atlas: [1, 2],
    drives: { energy: 0.9, curiosity: 0.88, affection: 0.72, playfulness: 0.96, confidence: 0.84, anger: 0.04 },
    instincts: { sleep: 0.48, play: 1.7, roam: 1.28, jump: 1.62, mischief: 1.06, affection: 1.04, temper: 0.26, petIrritation: -0.02, calmRate: 1.26 },
    movement: { speed: 1.3, jump: 1.24, toyForce: 1.14, ability: "web-sling" },
    favoriteToys: ["ball", "feather"]
  }),
  profile({
    id: "bastet",
    name: "Bastet",
    rarity: "legendary",
    tagline: "guardian of the oldest process",
    personality: "regal · patient · protective",
    special: "Raises an ancient ward before anger can take control.",
    atlasSet: "iteration-four-a",
    atlas: [2, 2],
    drives: { energy: 0.62, curiosity: 0.72, affection: 0.7, playfulness: 0.42, confidence: 1, anger: 0.02 },
    instincts: { sleep: 1.12, play: 0.76, roam: 1.02, jump: 0.9, mischief: 0.54, affection: 1.2, temper: 0.14, petIrritation: -0.045, calmRate: 1.9, hissThreshold: 0.8, clawThreshold: 0.94 },
    movement: { speed: 0.92, jump: 0.94, toyForce: 0.88, ability: "guardian-ward" },
    favoriteToys: ["box", "feather"]
  }),
  profile({
    id: "unsinkable-sam",
    name: "Unsinkable Sam",
    rarity: "rare",
    tagline: "always lands back on deck",
    personality: "unflappable · hardy · loyal",
    special: "Uses one of nine lives to recover from an off-screen fall without losing momentum.",
    atlasSet: "iteration-four-b",
    atlas: [0, 0],
    drives: { energy: 0.7, curiosity: 0.68, affection: 0.76, playfulness: 0.54, confidence: 0.98, anger: 0.08 },
    instincts: { sleep: 0.94, play: 0.94, roam: 1.3, jump: 1.1, mischief: 0.72, affection: 1.14, temper: 0.42, petIrritation: -0.025, calmRate: 1.3 },
    movement: { speed: 1.02, jump: 1.06, toyForce: 1.02, ability: "nine-lives" },
    favoriteToys: ["box", "ball"]
  }),
  profile({
    id: "trim",
    name: "Trim",
    rarity: "rare",
    tagline: "maps every unexplored surface",
    personality: "adventurous · observant · steadfast",
    special: "Remembers visited ledges and deliberately charts the least-explored route.",
    atlasSet: "iteration-four-b",
    atlas: [1, 0],
    drives: { energy: 0.8, curiosity: 0.99, affection: 0.58, playfulness: 0.64, confidence: 0.9, anger: 0.04 },
    instincts: { sleep: 0.62, play: 1.02, roam: 1.82, jump: 1.52, mischief: 0.68, affection: 0.84, temper: 0.24, petIrritation: -0.01, calmRate: 1.2 },
    movement: { speed: 1.18, jump: 1.12, toyForce: 0.94, ability: "navigator" },
    favoriteToys: ["laser", "feather"]
  }),
  profile({
    id: "snowball",
    name: "Snowball",
    rarity: "rare",
    tagline: "six toes make a better spin",
    personality: "bookish · dexterous · dignified",
    special: "Extra toes put a powerful curve and extra spin on every ball strike.",
    atlasSet: "iteration-four-b",
    atlas: [2, 0],
    drives: { energy: 0.58, curiosity: 0.9, affection: 0.68, playfulness: 0.7, confidence: 0.78, anger: 0.03 },
    instincts: { sleep: 1.06, play: 1.18, roam: 1.08, jump: 0.92, mischief: 0.62, affection: 1.06, temper: 0.2, petIrritation: -0.035, calmRate: 1.46 },
    movement: { speed: 0.88, jump: 0.92, toyForce: 1.38, ability: "extra-toes" },
    favoriteToys: ["ball", "box"]
  }),
  profile({
    id: "chonk",
    name: "Chonk",
    rarity: "common",
    tagline: "once the loaf lands, it stays landed",
    personality: "food-motivated · placid · immovable",
    special: "Becomes an immovable loaf while resting and lets every irritation roll away.",
    atlasSet: "iteration-four-b",
    atlas: [0, 1],
    visualScale: 1.1,
    drives: { energy: 0.3, curiosity: 0.32, affection: 0.78, playfulness: 0.24, confidence: 0.96, anger: 0.01 },
    instincts: { sleep: 1.9, play: 0.46, roam: 0.5, jump: 0.52, mischief: 0.28, affection: 1.32, temper: 0.12, petIrritation: -0.07, calmRate: 2.08 },
    movement: { speed: 0.48, jump: 0.66, toyForce: 1.5, ability: "immovable-loaf" },
    favoriteToys: ["box", "ball"]
  }),
  profile({
    id: "sphinx",
    name: "Sphinx",
    rarity: "rare",
    tagline: "the warmest pixel wins",
    personality: "warmth-seeking · affectionate · opinionated",
    special: "Seeks warm resting spots and recharges inside a cozy heat shimmer.",
    atlasSet: "iteration-four-b",
    atlas: [1, 1],
    visualScale: 0.88,
    drives: { energy: 0.44, curiosity: 0.7, affection: 0.96, playfulness: 0.5, confidence: 0.66, anger: 0.2 },
    instincts: { sleep: 1.56, play: 0.82, roam: 1.08, jump: 0.96, mischief: 0.42, affection: 1.82, temper: 0.72, petIrritation: 0.06, calmRate: 1.08, hissThreshold: 0.58, clawThreshold: 0.82 },
    movement: { speed: 0.9, jump: 0.98, toyForce: 0.78, ability: "heat-seeker" },
    favoriteToys: ["box", "feather"]
  })
]);

export const DEFAULT_CAT_ID = "byte";

export function getCatProfile(id) {
  return CAT_PROFILES.find((cat) => cat.id === id) || CAT_PROFILES[0];
}
